version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homepage
    ports:
      - '3001:3001'
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
